# -*- coding: utf-8 -*-
"""Zeynep Bastas - Salad Bar Machine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OPa0QAE7hKLjyJ3oVSLeDBlnGOltBqRw
"""

import time
menu = {
    "salatalik":10,
    "marul":12,
    "domates":15,
    "misir":9,
    "zeytin": 17,
    "roka": 16,
    "turp":11,
    "feslegen":8,
    "ceviz":9,
    "pancar":10,
}

class salad_bar_makinesi():

  def __init__(self, salad_bar_makinesinin_durumu = "Acik"):
     self.salad_barin_durumu = salad_barin_durumu

  def salad_bar_makinesini_ac(self):
      if (self.salad_bar_makinesinin_durumu == "Acik"):
            print("Makine acik")
      else:
        print("Makine aciliyor")
        self.salad_bar_makinesinin_durumu = "Acik"

  def salad_bar_makinesini_kapat(self):
      if (self.salad_bar_makinesinin_durumu == "Kapali"):
            print("Makine kapali")
      else:
        print("Makine kapatiliyor")
        print("BIZI TERCIH ETTIGINIZ ICIN TESEKKURLER!")
        self.salad_bar_makinesinin_durumu = "Kapali"

def display_menu():
     print("-----SALAD BAR MENU-----")
     for item in list(menu.keys()):
       print(f"{item.upper():<10} : {menu[item]} TL")

def malzeme_fiyat_hesaplama(malzeme, adet):
    assert adet >= 0 , "Malzeme 0 ve 0'dan kucuk olamaz"
    if malzeme not in list(menu.keys()):
      return None
    else:
      return menu[malzeme] * adet

def buy():
    display_menu()
    print("Hangi malzemeyi almak istiyorsunuz: (Cikis icin 0'i tuslayiniz.) ")

    satin_alinan_malzemeler = []
    satin_alinan_adet = []
    son_fiyat = 0

    while 1:
      eklenecek_malzeme = input("Hangi malzemeyi eklemeyi tercih edersiniz: ")

      if (eklenecek_malzeme == "0"):
        print("Fisiniz kaydediliyor")
        break

      eklenecek_adet = int(input("Sectiginiz malzemeden kac tane eklemek istiyorsunuz: "))
      fiyat = malzeme_fiyat_hesaplama(eklenecek_malzeme, eklenecek_adet)
      if fiyat is None:
            print("Hatali durum! Malzeme eklenemedi!")
      else:
        print(f"Satin alim ucreti: {fiyat}.\nSatin almayi onaylamak icin 'onay' iptal etmek icin 'iptal' yaziniz.")
        check = input("Satin almayi onayliyor musunuz? ")
        if check == "onay":
                print("Satın alim onaylandi.")
                print("-"*50)

        son_fiyat += fiyat

        satin_alinan_malzemeler.append(eklenecek_malzeme)

        satin_alinan_adet.append(eklenecek_adet)
        print(f"Ara Toplam: {son_fiyat}")

        if (check == "iptal"):
          print("Satin alma islemi iptal edildi")
          print("-"*50)

          return son_fiyat, satin_alinan_malzemeler, satin_alinan_adet

def main():
    print("Salad Bar'a Hos Geldiniz!\n Makineyi acmak icin 1'e \n Malzeme menusunu goruntulemek icin 2'ye, \n Salata yapmak icin 3'e, \n Makineyi kapatmak icin 4'e basiniz.")
    program = None
    while 1:
      program = int(input("Tercihiniz: "))
      if program < 0 or program > 4:
            print("Yanlis bir tusa bastiniz. Lutfen tekrar secim yapiniz.")

      elif program == 0:
        print("Cıkıs yapiliyor!")
        break

      elif program == 4:
        print("Makine kapatiliyor")
        break

      elif program ==1:
        print("Makine aciliyor")

      elif program == 2:
        display_menu()

      elif program == 3:
        satin_alma_ucreti, satin_alinan_malzemeler, satin_alinan_adet= buy()

        with open("kasa.txt","a") as f:
              f.write(str(time.ctime(time.time())))
              f.write("\n")
              f.write(','.join(map(str, satin_alinan_malzemeler)))
              f.write("\n")
              f.write(','.join(map(str, satin_alinan_adet)))
              f.write("\n")
              f.write(f"Toplam: {satin_alma_ucreti}")
              f.write("\n")
              f.write("*"*20)
              f.write("\n")

      cikis_kontrol = input("Baska bir isleminiz var mi? evet ya da hayir olarak cevap veriniz ")
      if cikis_kontrol == "evet":
        pass

      else:
        print("\n\nBizi tercih ettiginiz icin tesekkurler")
        break

main()